

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    IDPRO integer PRIMARY KEY,
    NOMPRO varchar2(50)  NOT NULL,
    PREPRO decimal(5,2)  NOT NULL,
    DESPRO varchar2(250)  NOT NULL,
    ESTPRO char(1)  NOT NULL,
    IDPROV INTEGER NOT NULL,
    STOPRO integer  NOT NULL,
    IMGPRO varchar2(200) NOT NULL
) ; 


CREATE SEQUENCE ID_PRODUCTO START WITH 1 INCREMENT BY 1 ORDER;



CREATE OR REPLACE TRIGGER ID_PRODUCTO BEFORE INSERT ON PRODUCTO FOR EACH ROW BEGIN SELECT ID_PRODUCTO.NEXTVAL INTO :NEW.IDPRO FROM DUAL;
END;



-- INSERTAR REGISTROS DE PRODUCTO 
    
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('TORTA DE CHOCOLATE', '57,0', 'SI DESEA ENDULZAR SU VIDA COMPRE SU RICA TORTA DE CHOCOLATE.','A','1','10','Producto1');
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('TORTA DE VAINILLA', '54,0','ES UNA TORTA ESPONJOSA','A','2','10','Producto2');
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('TORTA MARMOLEADO', '55,0','ES UN PASTEL DULCE CONTINE COCOA Y CACAO.','A','3','10','Producto3'); 
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('TORTA DE TRES LECHES', '50,0','CONSISTE EN UN BISCOCHO BA?ADO CON TRES TIPOS DE LECHE ','A','4','10','Producto4');
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('TORTA DE NARANJA', '40,0','CONTIENE LOS SABORES DEL JUGO DE NARANJA, RALLADURA DE LA CASCARA Y ESENCIA DE NARANJA.','A','5','10','Producto5');
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('TORTA HELADA', '45,0','TORTA HELADA ES TANTO UN HELADO CON FORMA DE TORTA.','A','6','10','Producto6');  
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('TORTA DE SELVA NEGRA', '53,0','LA TORTA SELVA NEGRA ES UNA TARTA TIPICA DE COCINA DE BADEN.','A','7','10','Producto7');
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('QUEQUE DE NARANJA',' 41,0', 'ES UN DELICIOSO Y CONTIENE NARANJA QUE TIENE PROPIEDADES BENIFICIOSOS.','A','8','10','Producto8');
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('QUEQUE DE LIMON', '43,0', 'ES UN QUEQUE FORMADA POR UNA BASE DE CREMA DE LIMON.','A','9','10','Producto9');
INSERT INTO PRODUCTO(NOMPRO,PREPRO,DESPRO,ESTPRO,IDPROV,STOPRO,IMGPRO) VALUES ('QUEQUE DE PI?A', '35,0', 'ESTE ES UN DELICIOSO QUEQUE CON UN CUBIERTO DE CARAMELO.','A','10','10','Producto10');




---Chart JS
CREATE OR REPLACE VIEW vGRAFICOSPRO
AS
SELECT 
NOMPRO AS Nombre, 
STOPRO AS Cantidad 
FROM PRODUCTO 
ORDER BY STOPRO DESC;
